"use client";

import { ComposeResult } from "@/lib/api";
import { Button, Card } from "./ui";

export function EmailPreview({
  rendered,
  recipient,
  gmailUser,
  onBack,
  onSend,
  sending,
}: {
  rendered: ComposeResult;
  recipient: string;
  gmailUser: string;
  onBack: () => void;
  onSend: () => void;
  sending: boolean;
}) {
  const isAI = rendered.source === "ai-tweaked";
  return (
    <Card title="Preview & send" step={2}>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <span
          className={`inline-flex items-center gap-1.5 rounded-[var(--radius-full)] px-2.5 py-1 text-xs font-medium ${
            isAI
              ? "bg-[var(--accent)]/10 text-[var(--accent)]"
              : "bg-[var(--muted)]/15 text-[var(--muted)]"
          }`}
          title={
            isAI
              ? "Your template, with an AI-tailored subject and one company-specific sentence."
              : "Your fixed template, no AI changes."
          }
        >
          {isAI ? "✨ Template + AI tweaks" : "📝 Template"}
        </span>
        {rendered.note && (
          <span className="text-xs text-[var(--warning-fg)]">{rendered.note}</span>
        )}
      </div>
      <div className="overflow-hidden rounded-[var(--radius-md)] border border-[var(--border)]">
        {/* Email header */}
        <div className="space-y-1 border-b border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm">
          <div className="flex gap-2">
            <span className="w-16 shrink-0 text-[var(--muted)]">From</span>
            <span className="font-medium">{gmailUser || "your Gmail"}</span>
          </div>
          <div className="flex gap-2">
            <span className="w-16 shrink-0 text-[var(--muted)]">To</span>
            <span className="font-medium">{recipient}</span>
          </div>
          <div className="flex gap-2">
            <span className="w-16 shrink-0 text-[var(--muted)]">Subject</span>
            <span className="font-semibold">{rendered.subject}</span>
          </div>
        </div>

        {/* Rendered HTML body — trusted, generated by our own backend template */}
        <div
          className="bg-white px-4 py-4 text-sm text-[#1a1a1a]"
          dangerouslySetInnerHTML={{ __html: rendered.bodyHTML }}
        />

        {/* Attachment chip */}
        <div className="flex items-center gap-2 border-t border-[var(--border)] bg-[var(--surface)] px-4 py-3">
          <span className="inline-flex items-center gap-2 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--elevated)] px-3 py-1.5 text-xs">
            📎 {rendered.attachmentName}
          </span>
          <span className="text-xs text-[var(--muted)]">Resume attached automatically</span>
        </div>
      </div>

      <div className="mt-5 flex flex-wrap items-center gap-3">
        <Button onClick={onSend} loading={sending}>
          Send email
        </Button>
        <Button variant="secondary" onClick={onBack} disabled={sending}>
          Back to edit
        </Button>
        <span className="text-xs text-[var(--muted)]">
          This sends a real email to {recipient}.
        </span>
      </div>
    </Card>
  );
}
